// Generated by gencpp from file ogreciti_paket/GecenZaman.msg
// DO NOT EDIT!


#ifndef OGRECITI_PAKET_MESSAGE_GECENZAMAN_H
#define OGRECITI_PAKET_MESSAGE_GECENZAMAN_H

#include <ros/service_traits.h>


#include <ogreciti_paket/GecenZamanRequest.h>
#include <ogreciti_paket/GecenZamanResponse.h>


namespace ogreciti_paket
{

struct GecenZaman
{

typedef GecenZamanRequest Request;
typedef GecenZamanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GecenZaman
} // namespace ogreciti_paket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ogreciti_paket::GecenZaman > {
  static const char* value()
  {
    return "d89a3e566b5de459800ae97d9237aa5b";
  }

  static const char* value(const ::ogreciti_paket::GecenZaman&) { return value(); }
};

template<>
struct DataType< ::ogreciti_paket::GecenZaman > {
  static const char* value()
  {
    return "ogreciti_paket/GecenZaman";
  }

  static const char* value(const ::ogreciti_paket::GecenZaman&) { return value(); }
};


// service_traits::MD5Sum< ::ogreciti_paket::GecenZamanRequest> should match
// service_traits::MD5Sum< ::ogreciti_paket::GecenZaman >
template<>
struct MD5Sum< ::ogreciti_paket::GecenZamanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ogreciti_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogreciti_paket::GecenZamanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ogreciti_paket::GecenZamanRequest> should match
// service_traits::DataType< ::ogreciti_paket::GecenZaman >
template<>
struct DataType< ::ogreciti_paket::GecenZamanRequest>
{
  static const char* value()
  {
    return DataType< ::ogreciti_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogreciti_paket::GecenZamanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ogreciti_paket::GecenZamanResponse> should match
// service_traits::MD5Sum< ::ogreciti_paket::GecenZaman >
template<>
struct MD5Sum< ::ogreciti_paket::GecenZamanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ogreciti_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogreciti_paket::GecenZamanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ogreciti_paket::GecenZamanResponse> should match
// service_traits::DataType< ::ogreciti_paket::GecenZaman >
template<>
struct DataType< ::ogreciti_paket::GecenZamanResponse>
{
  static const char* value()
  {
    return DataType< ::ogreciti_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogreciti_paket::GecenZamanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OGRECITI_PAKET_MESSAGE_GECENZAMAN_H
