// Generated by gencpp from file suruiha_gazebo_plugins/AirTrafficRequest.msg
// DO NOT EDIT!


#ifndef SURUIHA_GAZEBO_PLUGINS_MESSAGE_AIRTRAFFICREQUEST_H
#define SURUIHA_GAZEBO_PLUGINS_MESSAGE_AIRTRAFFICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace suruiha_gazebo_plugins
{
template <class ContainerAllocator>
struct AirTrafficRequest_
{
  typedef AirTrafficRequest_<ContainerAllocator> Type;

  AirTrafficRequest_()
    : sender()
    , command()  {
    }
  AirTrafficRequest_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AirTrafficRequest_

typedef ::suruiha_gazebo_plugins::AirTrafficRequest_<std::allocator<void> > AirTrafficRequest;

typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficRequest > AirTrafficRequestPtr;
typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficRequest const> AirTrafficRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator1> & lhs, const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sender == rhs.sender &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator1> & lhs, const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace suruiha_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4186925a01ff9bcfb4981fca37de73f5";
  }

  static const char* value(const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4186925a01ff9bcfULL;
  static const uint64_t static_value2 = 0xb4981fca37de73f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "suruiha_gazebo_plugins/AirTrafficRequest";
  }

  static const char* value(const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n"
"string command\n"
;
  }

  static const char* value(const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AirTrafficRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::suruiha_gazebo_plugins::AirTrafficRequest_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURUIHA_GAZEBO_PLUGINS_MESSAGE_AIRTRAFFICREQUEST_H
