// Generated by gencpp from file suruiha_gazebo_plugins/AirTrafficResponse.msg
// DO NOT EDIT!


#ifndef SURUIHA_GAZEBO_PLUGINS_MESSAGE_AIRTRAFFICRESPONSE_H
#define SURUIHA_GAZEBO_PLUGINS_MESSAGE_AIRTRAFFICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace suruiha_gazebo_plugins
{
template <class ContainerAllocator>
struct AirTrafficResponse_
{
  typedef AirTrafficResponse_<ContainerAllocator> Type;

  AirTrafficResponse_()
    : result()  {
    }
  AirTrafficResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AirTrafficResponse_

typedef ::suruiha_gazebo_plugins::AirTrafficResponse_<std::allocator<void> > AirTrafficResponse;

typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficResponse > AirTrafficResponsePtr;
typedef boost::shared_ptr< ::suruiha_gazebo_plugins::AirTrafficResponse const> AirTrafficResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator1> & lhs, const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator1> & lhs, const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace suruiha_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "suruiha_gazebo_plugins/AirTrafficResponse";
  }

  static const char* value(const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AirTrafficResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::suruiha_gazebo_plugins::AirTrafficResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURUIHA_GAZEBO_PLUGINS_MESSAGE_AIRTRAFFICRESPONSE_H
