// Generated by gencpp from file suruiha_gazebo_plugins/UAVMessage.msg
// DO NOT EDIT!


#ifndef SURUIHA_GAZEBO_PLUGINS_MESSAGE_UAVMESSAGE_H
#define SURUIHA_GAZEBO_PLUGINS_MESSAGE_UAVMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace suruiha_gazebo_plugins
{
template <class ContainerAllocator>
struct UAVMessage_
{
  typedef UAVMessage_<ContainerAllocator> Type;

  UAVMessage_()
    : sender()
    , msg()  {
    }
  UAVMessage_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> const> ConstPtr;

}; // struct UAVMessage_

typedef ::suruiha_gazebo_plugins::UAVMessage_<std::allocator<void> > UAVMessage;

typedef boost::shared_ptr< ::suruiha_gazebo_plugins::UAVMessage > UAVMessagePtr;
typedef boost::shared_ptr< ::suruiha_gazebo_plugins::UAVMessage const> UAVMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator1> & lhs, const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator2> & rhs)
{
  return lhs.sender == rhs.sender &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator1> & lhs, const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace suruiha_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18c52e8ab8398610a60c4f15e277c64d";
  }

  static const char* value(const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18c52e8ab8398610ULL;
  static const uint64_t static_value2 = 0xa60c4f15e277c64dULL;
};

template<class ContainerAllocator>
struct DataType< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "suruiha_gazebo_plugins/UAVMessage";
  }

  static const char* value(const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n"
"string msg\n"
;
  }

  static const char* value(const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UAVMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::suruiha_gazebo_plugins::UAVMessage_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURUIHA_GAZEBO_PLUGINS_MESSAGE_UAVMESSAGE_H
